const allTasks = [
  {
    id: 1,
    title: 'Task 1',
    description:
      'This is a random description for Task 1 This is a random description for Task 1 This is a random description for Task 1',
    status: 'documentation',
    end: '2023-09-25',
    assignee: 'John Doe',
    completed: true,
    priority: 'medium',
    project_id: 1,
    user_id: 1,
    start: '2023-09-20',
  },
  {
    id: 2,
    title: 'Task 2',
    description: 'This is a random description for Task 2',
    status: 'to_do',
    end: '2023-09-26',
    assignee: 'Alice Smith',
    completed: false,
    priority: 'easy',
    project_id: 2,
    user_id: 2,
    start: '2023-09-21',
  },
  {
    id: 3,
    title: 'Task 3',
    description: 'This is a random description for Task 3',
    status: 'ongoing',
    end: '2023-09-27',
    assignee: 'Bob Johnson',
    completed: false,
    priority: 'medium',
    project_id: 3,
    user_id: 3,
    start: '2023-09-22',
  },
  {
    id: 4,
    title: 'Task 4',
    description: 'This is a random description for Task 4',
    status: 'done',
    end: '2023-09-28',
    assignee: 'Eva Brown',
    completed: true,
    priority: 'hard',
    project_id: 4,
    user_id: 4,
    start: '2023-09-18',
  },
  {
    id: 5,
    title: 'Task 5',
    description: 'This is a random description for Task 5',
    status: 'documentation',
    end: '2023-09-29',
    assignee: 'Michael Lee',
    completed: false,
    priority: 'easy',
    project_id: 5,
    user_id: 5,
    start: '2023-09-16',
  },
  {
    id: 6,
    title: 'Task 6',
    description: 'This is a random description for Task 6',
    status: 'to_do',
    end: '2023-09-30',
    assignee: 'John Doe',
    completed: false,
    priority: 'medium',
    project_id: 1,
    user_id: 1,
    start: '2023-09-19',
  },
  {
    id: 7,
    title: 'Task 7',
    description: 'This is a random description for Task 7',
    status: 'ongoing',
    end: '2023-10-01',
    assignee: 'Alice Smith',
    completed: false,
    priority: 'medium',
    project_id: 2,
    user_id: 2,
    start: '2023-09-27',
  },
  {
    id: 8,
    title: 'Task 8',
    description: 'This is a random description for Task 8',
    status: 'done',
    end: '2023-10-02',
    assignee: 'Bob Johnson',
    completed: true,
    priority: 'hard',
    project_id: 3,
    user_id: 3,
    start: '2023-09-27',
  },
  {
    id: 9,
    title: 'Task 9',
    description: 'This is a random description for Task 9',
    status: 'documentation',
    end: '2023-10-03',
    assignee: 'Eva Brown',
    completed: true,
    priority: 'easy',
    project_id: 4,
    user_id: 2,
    start: '2023-09-29',
  },
  {
    id: 10,
    title: 'Task 10',
    description: 'This is a random description for Task 10',
    status: 'to_do',
    end: '2023-10-04',
    assignee: 'Michael Lee',
    completed: false,
    priority: 'medium',
    project_id: 5,
    user_id: 5,
    start: '2023-10-01',
  },
  {
    id: 11,
    title: 'Task 11',
    description: 'This is a random description for Task 11',
    status: 'ongoing',
    end: '2023-10-05',
    assignee: 'John Doe',
    completed: false,
    priority: 'easy',
    project_id: 1,
    user_id: 1,
    start: '2023-10-01',
  },
  {
    id: 12,
    title: 'Task 12',
    description: 'This is a random description for Task 12',
    status: 'done',
    end: '2023-10-06',
    assignee: 'Alice Smith',
    completed: true,
    priority: 'hard',
    project_id: 2,
    user_id: 2,
    start: '2023-10-02',
  },
  {
    id: 13,
    title: 'Task 13',
    description: 'This is a random description for Task 13',
    status: 'documentation',
    end: '2023-10-07',
    assignee: 'Bob Johnson',
    completed: false,
    priority: 'medium',
    project_id: 3,
    user_id: 3,
    start: '2023-10-03',
  },
  {
    id: 14,
    title: 'Task 14',
    description: 'This is a random description for Task 14',
    status: 'to_do',
    end: '2023-10-08',
    assignee: 'Eva Brown',
    completed: false,
    priority: 'medium',
    project_id: 4,
    user_id: 4,
    start: '2023-10-05',
  },
  {
    id: 15,
    title: 'Task 15',
    description: 'This is a random description for Task 15',
    status: 'ongoing',
    end: '2023-10-09',
    assignee: 'Michael Lee',
    completed: true,
    priority: 'easy',
    project_id: 5,
    user_id: 3,
    start: '2023-10-07',
  },
  {
    id: 16,
    title: 'Task 16',
    description: 'This is a random description for Task 16',
    status: 'done',
    end: '2023-10-10',
    assignee: 'John Doe',
    completed: true,
    priority: 'medium',
    project_id: 1,
    user_id: 1,
    start: '2023-10-06',
  },
  {
    id: 17,
    title: 'Task 17',
    description: 'This is a random description for Task 17',
    status: 'documentation',
    end: '2023-10-11',
    assignee: 'Alice Smith',
    completed: false,
    priority: 'medium',
    project_id: 2,
    user_id: 2,
    start: '2023-10-9',
  },
  {
    id: 18,
    title: 'Task 18',
    description: 'This is a random description for Task 18',
    status: 'to_do',
    end: '2023-10-12',
    assignee: 'Bob Johnson',
    completed: false,
    priority: 'hard',
    project_id: 3,
    user_id: 3,
    start: '2023-10-08',
  },
  {
    id: 19,
    title: 'Task 19',
    description: 'This is a random description for Task 19',
    status: 'ongoing',
    end: '2023-10-13',
    assignee: 'Eva Brown',
    completed: true,
    priority: 'easy',
    project_id: 4,
    user_id: 4,
    start: '2023-10-10',
  },
  {
    id: 20,
    title: 'Task 20',
    description: 'This is a random description for Task 20',
    status: 'done',
    end: '2023-10-14',
    assignee: 'Michael Lee',
    completed: true,
    priority: 'medium',
    project_id: 5,
    user_id: 5,
    start: '2023-10-10',
  },
  {
    id: 21,
    title: 'Task 21',
    description: 'This is a random description for Task 21',
    status: 'documentation',
    end: '2023-09-25',
    assignee: 'John Doe',
    completed: true,
    priority: 'medium',
    project_id: 1,
    user_id: 1,
    start: '2023-09-19',
  },
];

export default allTasks;
